# coding: utf-8

"""
    PromptJuggler

    PromptJuggler API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from promptjuggler._generated.models.create_workflow_run_metadata_value import CreateWorkflowRunMetadataValue
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreateWorkflowRun(BaseModel):
    """
    Request payload for creating a workflow run.
    """ # noqa: E501
    inputs: Dict[str, StrictStr] = Field(description="Key-value map of input variable names to their values.", json_schema_extra={"examples": [{"topic": "AI safety"}]})
    thread: Optional[UUID] = Field(default=None, description="Thread ID to continue a multi-turn conversation. Omit to start a new thread.")
    priority: Optional[StrictStr] = Field(default='normal', description="Processing priority.")
    environment: Optional[StrictStr] = Field(default=None, description="Environment that scopes which webhooks fire and which environment variables the run can access. Uses the default environment when omitted.")
    env_vars: Optional[Dict[str, StrictStr]] = Field(default=None, description="Runtime environment variable overrides for this run. Keys must be UPPER_CASE. At most 50 entries, 64 KB total.", alias="envVars", json_schema_extra={"examples": [{"MY_API_KEY": "sk-..."}]})
    metadata: Optional[Dict[str, CreateWorkflowRunMetadataValue]] = Field(default=None, description="Arbitrary key-value metadata attached to the run. Values can be strings or arrays of strings.", json_schema_extra={"examples": [{"user_id": "42"}]})
    __properties: ClassVar[List[str]] = ["inputs", "thread", "priority", "environment", "envVars", "metadata"]

    @field_validator('priority')
    def priority_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['onsite', 'normal', 'low']):
            raise ValueError("must be one of enum values ('onsite', 'normal', 'low')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateWorkflowRun from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in metadata (dict)
        _field_dict = {}
        if self.metadata:
            for _key_metadata in self.metadata:
                if self.metadata[_key_metadata]:
                    _field_dict[_key_metadata] = self.metadata[_key_metadata].to_dict()
            _dict['metadata'] = _field_dict
        # set to None if thread (nullable) is None
        # and model_fields_set contains the field
        if self.thread is None and "thread" in self.model_fields_set:
            _dict['thread'] = None

        # set to None if environment (nullable) is None
        # and model_fields_set contains the field
        if self.environment is None and "environment" in self.model_fields_set:
            _dict['environment'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateWorkflowRun from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "inputs": obj.get("inputs"),
            "thread": obj.get("thread"),
            "priority": obj.get("priority") if obj.get("priority") is not None else 'normal',
            "environment": obj.get("environment"),
            "envVars": obj.get("envVars"),
            "metadata": dict(
                (_k, CreateWorkflowRunMetadataValue.from_dict(_v))
                for _k, _v in obj["metadata"].items()
            )
            if obj.get("metadata") is not None
            else None
        })
        return _obj


