# coding: utf-8

"""
    PromptJuggler

    PromptJuggler API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Mcp(BaseModel):
    """
    Built-in MCP server tool.
    """ # noqa: E501
    name: Annotated[str, Field(strict=True)] = Field(description="The MCP server tool’s name.")
    url: StrictStr = Field(description="The URL of the MCP server.")
    authorization_token: Optional[StrictStr] = Field(default=None, description="Authorization token for the MCP server.", alias="authorizationToken")
    allowed_tools: Optional[List[StrictStr]] = Field(default=None, description="Tool names the model may call. Empty or omitted allows all of the server’s tools.", alias="allowedTools")
    type: StrictStr
    __properties: ClassVar[List[str]] = ["name", "url", "authorizationToken", "allowedTools", "type"]

    @field_validator('name')
    def name_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"[a-zA-Z0-9_-]+", value):
            raise ValueError(r"must validate the regular expression /[a-zA-Z0-9_-]+/")
        return value

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['mcp']):
            raise ValueError("must be one of enum values ('mcp')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Mcp from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if authorization_token (nullable) is None
        # and model_fields_set contains the field
        if self.authorization_token is None and "authorization_token" in self.model_fields_set:
            _dict['authorizationToken'] = None

        # set to None if allowed_tools (nullable) is None
        # and model_fields_set contains the field
        if self.allowed_tools is None and "allowed_tools" in self.model_fields_set:
            _dict['allowedTools'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Mcp from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "url": obj.get("url"),
            "authorizationToken": obj.get("authorizationToken"),
            "allowedTools": obj.get("allowedTools"),
            "type": obj.get("type")
        })
        return _obj


