# coding: utf-8

"""
    PromptJuggler

    PromptJuggler API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class Memory(str, Enum):
    """
    Memory
    """

    """
    allowed enum values
    """
    STATELESS = 'stateless'
    READ_ONLY = 'read_only'
    READ_WRITE = 'read_write'
    WRITE_ONLY = 'write_only'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Memory from a JSON string"""
        return cls(json.loads(json_str))


