# coding: utf-8

"""
    PromptJuggler

    PromptJuggler API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from promptjuggler._generated.models.service_tier import ServiceTier
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ModelParams(BaseModel):
    """
    AI model parameters.
    """ # noqa: E501
    max_completion_tokens: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Maximum completion tokens.", alias="maxCompletionTokens")
    temperature: Optional[Union[Annotated[float, Field(le=2, strict=True, ge=0)], Annotated[int, Field(le=2, strict=True, ge=0)]]] = Field(default=None, description="Temperature.")
    top_p: Optional[Union[Annotated[float, Field(le=2, strict=True, ge=0)], Annotated[int, Field(le=2, strict=True, ge=0)]]] = Field(default=None, description="Top P.", alias="topP")
    verbosity: Optional[StrictStr] = Field(default=None, description="Verbosity.")
    reasoning_effort: Optional[StrictStr] = Field(default=None, description="Reasoning effort.", alias="reasoningEffort")
    reasoning_summary: Optional[StrictBool] = Field(default=None, description="Return reasoning summary.", alias="reasoningSummary")
    service_tier: Optional[ServiceTier] = Field(default=None, description="Service tier.", alias="serviceTier")
    __properties: ClassVar[List[str]] = ["maxCompletionTokens", "temperature", "topP", "verbosity", "reasoningEffort", "reasoningSummary", "serviceTier"]

    @field_validator('verbosity')
    def verbosity_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['low', 'medium', 'high']):
            raise ValueError("must be one of enum values ('low', 'medium', 'high')")
        return value

    @field_validator('reasoning_effort')
    def reasoning_effort_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['none', 'low', 'medium', 'high', 'xhigh', 'max']):
            raise ValueError("must be one of enum values ('none', 'low', 'medium', 'high', 'xhigh', 'max')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ModelParams from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if max_completion_tokens (nullable) is None
        # and model_fields_set contains the field
        if self.max_completion_tokens is None and "max_completion_tokens" in self.model_fields_set:
            _dict['maxCompletionTokens'] = None

        # set to None if temperature (nullable) is None
        # and model_fields_set contains the field
        if self.temperature is None and "temperature" in self.model_fields_set:
            _dict['temperature'] = None

        # set to None if top_p (nullable) is None
        # and model_fields_set contains the field
        if self.top_p is None and "top_p" in self.model_fields_set:
            _dict['topP'] = None

        # set to None if verbosity (nullable) is None
        # and model_fields_set contains the field
        if self.verbosity is None and "verbosity" in self.model_fields_set:
            _dict['verbosity'] = None

        # set to None if reasoning_effort (nullable) is None
        # and model_fields_set contains the field
        if self.reasoning_effort is None and "reasoning_effort" in self.model_fields_set:
            _dict['reasoningEffort'] = None

        # set to None if reasoning_summary (nullable) is None
        # and model_fields_set contains the field
        if self.reasoning_summary is None and "reasoning_summary" in self.model_fields_set:
            _dict['reasoningSummary'] = None

        # set to None if service_tier (nullable) is None
        # and model_fields_set contains the field
        if self.service_tier is None and "service_tier" in self.model_fields_set:
            _dict['serviceTier'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ModelParams from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "maxCompletionTokens": obj.get("maxCompletionTokens"),
            "temperature": obj.get("temperature"),
            "topP": obj.get("topP"),
            "verbosity": obj.get("verbosity"),
            "reasoningEffort": obj.get("reasoningEffort"),
            "reasoningSummary": obj.get("reasoningSummary"),
            "serviceTier": obj.get("serviceTier")
        })
        return _obj


