# coding: utf-8

"""
    PromptJuggler

    PromptJuggler API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class Model(str, Enum):
    """
    Model
    """

    """
    allowed enum values
    """
    GPT_MINUS_5_DOT_5 = 'gpt-5.5'
    GPT_MINUS_5_DOT_5_MINUS_PRO = 'gpt-5.5-pro'
    GPT_MINUS_5_DOT_4 = 'gpt-5.4'
    GPT_MINUS_5_DOT_4_MINUS_MINI = 'gpt-5.4-mini'
    GPT_MINUS_5_DOT_4_MINUS_NANO = 'gpt-5.4-nano'
    GPT_MINUS_5_DOT_4_MINUS_PRO = 'gpt-5.4-pro'
    GPT_MINUS_5_DOT_2 = 'gpt-5.2'
    GPT_MINUS_5_DOT_2_MINUS_PRO = 'gpt-5.2-pro'
    GPT_MINUS_5_DOT_1 = 'gpt-5.1'
    GPT_MINUS_4_DOT_1 = 'gpt-4.1'
    GPT_MINUS_4_DOT_1_MINUS_MINI = 'gpt-4.1-mini'
    GPT_MINUS_4O = 'gpt-4o'
    GPT_MINUS_4O_MINUS_MINI = 'gpt-4o-mini'
    GEMINI_MINUS_3_DOT_1_MINUS_PRO_MINUS_PREVIEW = 'gemini-3.1-pro-preview'
    GEMINI_MINUS_3_DOT_5_MINUS_FLASH = 'gemini-3.5-flash'
    GEMINI_MINUS_3_MINUS_FLASH_MINUS_PREVIEW = 'gemini-3-flash-preview'
    GEMINI_MINUS_3_DOT_1_MINUS_FLASH_MINUS_LITE = 'gemini-3.1-flash-lite'
    GEMINI_MINUS_2_DOT_5_MINUS_PRO = 'gemini-2.5-pro'
    GEMINI_MINUS_2_DOT_5_MINUS_FLASH = 'gemini-2.5-flash'
    GEMINI_MINUS_2_DOT_5_MINUS_FLASH_MINUS_LITE = 'gemini-2.5-flash-lite'
    CLAUDE_MINUS_OPUS_MINUS_4_MINUS_8 = 'claude-opus-4-8'
    CLAUDE_MINUS_OPUS_MINUS_4_MINUS_7 = 'claude-opus-4-7'
    CLAUDE_MINUS_OPUS_MINUS_4_MINUS_6 = 'claude-opus-4-6'
    CLAUDE_MINUS_OPUS_MINUS_4_MINUS_5 = 'claude-opus-4-5'
    CLAUDE_MINUS_SONNET_MINUS_4_MINUS_6 = 'claude-sonnet-4-6'
    CLAUDE_MINUS_SONNET_MINUS_4_MINUS_5 = 'claude-sonnet-4-5'
    CLAUDE_MINUS_HAIKU_MINUS_4_MINUS_5 = 'claude-haiku-4-5'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Model from a JSON string"""
        return cls(json.loads(json_str))


