# coding: utf-8

"""
    PromptJuggler

    PromptJuggler API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from promptjuggler._generated.models.content_message_response import ContentMessageResponse
from promptjuggler._generated.models.memory import Memory
from promptjuggler._generated.models.model import Model
from promptjuggler._generated.models.model_params import ModelParams
from promptjuggler._generated.models.provider import Provider
from promptjuggler._generated.models.response_format import ResponseFormat
from promptjuggler._generated.models.tool import Tool
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PromptRevision(BaseModel):
    """
    Prompt revision
    """ # noqa: E501
    id: UUID = Field(description="Prompt revision ID.")
    prompt_id: UUID = Field(description="Prompt ID.", alias="promptId")
    memory: Memory = Field(description="Memory mode.")
    provider: Provider = Field(description="AI provider.")
    model: Model = Field(description="AI model.")
    model_params: ModelParams = Field(description="Model parameters.", alias="modelParams")
    response_format: ResponseFormat = Field(description="AI model response format.", alias="responseFormat")
    system_instruction: Optional[StrictStr] = Field(default=None, description="The system prompt.", alias="systemInstruction")
    messages: List[ContentMessageResponse] = Field(description="User and assistant messages.")
    tools: List[Tool] = Field(description="Available tools.")
    __properties: ClassVar[List[str]] = ["id", "promptId", "memory", "provider", "model", "modelParams", "responseFormat", "systemInstruction", "messages", "tools"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PromptRevision from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of model_params
        if self.model_params:
            _dict['modelParams'] = self.model_params.to_dict()
        # override the default output from pydantic by calling `to_dict()` of response_format
        if self.response_format:
            _dict['responseFormat'] = self.response_format.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in messages (list)
        _items = []
        if self.messages:
            for _item_messages in self.messages:
                if _item_messages:
                    _items.append(_item_messages.to_dict())
            _dict['messages'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in tools (list)
        _items = []
        if self.tools:
            for _item_tools in self.tools:
                if _item_tools:
                    _items.append(_item_tools.to_dict())
            _dict['tools'] = _items
        # set to None if system_instruction (nullable) is None
        # and model_fields_set contains the field
        if self.system_instruction is None and "system_instruction" in self.model_fields_set:
            _dict['systemInstruction'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PromptRevision from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "promptId": obj.get("promptId"),
            "memory": obj.get("memory"),
            "provider": obj.get("provider"),
            "model": obj.get("model"),
            "modelParams": ModelParams.from_dict(obj["modelParams"]) if obj.get("modelParams") is not None else None,
            "responseFormat": ResponseFormat.from_dict(obj["responseFormat"]) if obj.get("responseFormat") is not None else None,
            "systemInstruction": obj.get("systemInstruction"),
            "messages": [ContentMessageResponse.from_dict(_item) for _item in obj["messages"]] if obj.get("messages") is not None else None,
            "tools": [Tool.from_dict(_item) for _item in obj["tools"]] if obj.get("tools") is not None else None
        })
        return _obj


