# coding: utf-8

"""
    PromptJuggler

    PromptJuggler API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from promptjuggler._generated.models.version_ref import VersionRef
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PromptCall(BaseModel):
    """
    Tool to invoke another prompt.
    """ # noqa: E501
    version_ref: VersionRef = Field(description="Referencing the prompt revision either by id or version number or tag.", alias="versionRef")
    name: Annotated[str, Field(strict=True)] = Field(description="The tool’s name.")
    description: Optional[StrictStr] = Field(default=None, description="The tool’s description.")
    fail_fast: Optional[StrictBool] = Field(default=False, description="Whether to stop processing if a tool call fails.", alias="failFast")
    type: StrictStr
    __properties: ClassVar[List[str]] = ["versionRef", "name", "description", "failFast", "type"]

    @field_validator('name')
    def name_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"[a-zA-Z0-9_-]+", value):
            raise ValueError(r"must validate the regular expression /[a-zA-Z0-9_-]+/")
        return value

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['prompt']):
            raise ValueError("must be one of enum values ('prompt')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PromptCall from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of version_ref
        if self.version_ref:
            _dict['versionRef'] = self.version_ref.to_dict()
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PromptCall from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "versionRef": VersionRef.from_dict(obj["versionRef"]) if obj.get("versionRef") is not None else None,
            "name": obj.get("name"),
            "description": obj.get("description"),
            "failFast": obj.get("failFast") if obj.get("failFast") is not None else False,
            "type": obj.get("type")
        })
        return _obj


