# coding: utf-8

"""
    PromptJuggler

    PromptJuggler API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from promptjuggler._generated.models.run_cost import RunCost
from promptjuggler._generated.models.run_status import RunStatus
from promptjuggler._generated.models.token_usage import TokenUsage
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PromptRun(BaseModel):
    """
    Prompt run status and result.
    """ # noqa: E501
    id: UUID = Field(description="Prompt run ID.")
    status: RunStatus = Field(description="Current run status.")
    created_at: datetime = Field(description="Timestamp when the run was created.", alias="createdAt")
    finished_at: Optional[datetime] = Field(default=None, description="Timestamp when the run finished. Null while the run is pending.", alias="finishedAt")
    output: Optional[StrictStr] = Field(default=None, description="LLM output text. Null while pending or when the run failed.")
    error: Optional[StrictStr] = Field(default=None, description="Error message if the run failed. Null on success.")
    token_usage: Optional[TokenUsage] = Field(default=None, description="Token usage for the successful run. Null while pending or when the run failed.", alias="tokenUsage")
    cost: Optional[RunCost] = Field(default=None, description="Cost breakdown for the run. Null while pending.")
    __properties: ClassVar[List[str]] = ["id", "status", "createdAt", "finishedAt", "output", "error", "tokenUsage", "cost"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PromptRun from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of token_usage
        if self.token_usage:
            _dict['tokenUsage'] = self.token_usage.to_dict()
        # override the default output from pydantic by calling `to_dict()` of cost
        if self.cost:
            _dict['cost'] = self.cost.to_dict()
        # set to None if finished_at (nullable) is None
        # and model_fields_set contains the field
        if self.finished_at is None and "finished_at" in self.model_fields_set:
            _dict['finishedAt'] = None

        # set to None if output (nullable) is None
        # and model_fields_set contains the field
        if self.output is None and "output" in self.model_fields_set:
            _dict['output'] = None

        # set to None if error (nullable) is None
        # and model_fields_set contains the field
        if self.error is None and "error" in self.model_fields_set:
            _dict['error'] = None

        # set to None if token_usage (nullable) is None
        # and model_fields_set contains the field
        if self.token_usage is None and "token_usage" in self.model_fields_set:
            _dict['tokenUsage'] = None

        # set to None if cost (nullable) is None
        # and model_fields_set contains the field
        if self.cost is None and "cost" in self.model_fields_set:
            _dict['cost'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PromptRun from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "status": obj.get("status"),
            "createdAt": obj.get("createdAt"),
            "finishedAt": obj.get("finishedAt"),
            "output": obj.get("output"),
            "error": obj.get("error"),
            "tokenUsage": TokenUsage.from_dict(obj["tokenUsage"]) if obj.get("tokenUsage") is not None else None,
            "cost": RunCost.from_dict(obj["cost"]) if obj.get("cost") is not None else None
        })
        return _obj


