# coding: utf-8

"""
    PromptJuggler

    PromptJuggler API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class Provider(str, Enum):
    """
    Provider
    """

    """
    allowed enum values
    """
    OPENAI = 'openai'
    GEMINI = 'gemini'
    ANTHROPIC = 'anthropic'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Provider from a JSON string"""
        return cls(json.loads(json_str))


