# coding: utf-8

"""
    PromptJuggler

    PromptJuggler API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ServiceTier(str, Enum):
    """
    ServiceTier
    """

    """
    allowed enum values
    """
    AUTO = 'auto'
    DEFAULT = 'default'
    FLEX = 'flex'
    PRIORITY = 'priority'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ServiceTier from a JSON string"""
        return cls(json.loads(json_str))


