# coding: utf-8

"""
    PromptJuggler

    PromptJuggler API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from promptjuggler._generated.models.http_call import HttpCall
from promptjuggler._generated.models.knowledge_search import KnowledgeSearch
from promptjuggler._generated.models.mcp import Mcp
from promptjuggler._generated.models.prompt_call import PromptCall
from promptjuggler._generated.models.script_call import ScriptCall
from promptjuggler._generated.models.web_search import WebSearch
from promptjuggler._generated.models.workflow_call import WorkflowCall
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

TOOL_ONE_OF_SCHEMAS = ["HttpCall", "KnowledgeSearch", "Mcp", "PromptCall", "ScriptCall", "WebSearch", "WorkflowCall"]

class Tool(BaseModel):
    """
    Tool
    """
    # data type: WebSearch
    oneof_schema_1_validator: Optional[WebSearch] = None
    # data type: HttpCall
    oneof_schema_2_validator: Optional[HttpCall] = None
    # data type: ScriptCall
    oneof_schema_3_validator: Optional[ScriptCall] = None
    # data type: Mcp
    oneof_schema_4_validator: Optional[Mcp] = None
    # data type: PromptCall
    oneof_schema_5_validator: Optional[PromptCall] = None
    # data type: WorkflowCall
    oneof_schema_6_validator: Optional[WorkflowCall] = None
    # data type: KnowledgeSearch
    oneof_schema_7_validator: Optional[KnowledgeSearch] = None
    actual_instance: Optional[Union[HttpCall, KnowledgeSearch, Mcp, PromptCall, ScriptCall, WebSearch, WorkflowCall]] = None
    one_of_schemas: Set[str] = { "HttpCall", "KnowledgeSearch", "Mcp", "PromptCall", "ScriptCall", "WebSearch", "WorkflowCall" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = Tool.model_construct()
        error_messages = []
        match = 0
        # validate data type: WebSearch
        if not isinstance(v, WebSearch):
            error_messages.append(f"Error! Input type `{type(v)}` is not `WebSearch`")
        else:
            match += 1
        # validate data type: HttpCall
        if not isinstance(v, HttpCall):
            error_messages.append(f"Error! Input type `{type(v)}` is not `HttpCall`")
        else:
            match += 1
        # validate data type: ScriptCall
        if not isinstance(v, ScriptCall):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ScriptCall`")
        else:
            match += 1
        # validate data type: Mcp
        if not isinstance(v, Mcp):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Mcp`")
        else:
            match += 1
        # validate data type: PromptCall
        if not isinstance(v, PromptCall):
            error_messages.append(f"Error! Input type `{type(v)}` is not `PromptCall`")
        else:
            match += 1
        # validate data type: WorkflowCall
        if not isinstance(v, WorkflowCall):
            error_messages.append(f"Error! Input type `{type(v)}` is not `WorkflowCall`")
        else:
            match += 1
        # validate data type: KnowledgeSearch
        if not isinstance(v, KnowledgeSearch):
            error_messages.append(f"Error! Input type `{type(v)}` is not `KnowledgeSearch`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in Tool with oneOf schemas: HttpCall, KnowledgeSearch, Mcp, PromptCall, ScriptCall, WebSearch, WorkflowCall. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in Tool with oneOf schemas: HttpCall, KnowledgeSearch, Mcp, PromptCall, ScriptCall, WebSearch, WorkflowCall. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into WebSearch
        try:
            instance.actual_instance = WebSearch.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into HttpCall
        try:
            instance.actual_instance = HttpCall.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ScriptCall
        try:
            instance.actual_instance = ScriptCall.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into Mcp
        try:
            instance.actual_instance = Mcp.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into PromptCall
        try:
            instance.actual_instance = PromptCall.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into WorkflowCall
        try:
            instance.actual_instance = WorkflowCall.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into KnowledgeSearch
        try:
            instance.actual_instance = KnowledgeSearch.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into Tool with oneOf schemas: HttpCall, KnowledgeSearch, Mcp, PromptCall, ScriptCall, WebSearch, WorkflowCall. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into Tool with oneOf schemas: HttpCall, KnowledgeSearch, Mcp, PromptCall, ScriptCall, WebSearch, WorkflowCall. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], HttpCall, KnowledgeSearch, Mcp, PromptCall, ScriptCall, WebSearch, WorkflowCall]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


