# coding: utf-8

"""
    PromptJuggler

    PromptJuggler API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from promptjuggler._generated.models.citation import Citation
from promptjuggler._generated.models.tool_status import ToolStatus
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TranscriptTool(BaseModel):
    """
    A tool the model used: its name and how the call ended.
    """ # noqa: E501
    name: StrictStr = Field(description="Tool name, as the model called it.")
    status: ToolStatus = Field(description="How the call ended.")
    queries: List[StrictStr] = Field(description="Search queries the model ran. Only ever populated by the built-in web_search tool.")
    citations: List[Citation] = Field(description="Sources this call returned. Only ever populated by the built-in web_search tool.")
    type: StrictStr
    __properties: ClassVar[List[str]] = ["name", "status", "queries", "citations", "type"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['tool']):
            raise ValueError("must be one of enum values ('tool')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TranscriptTool from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in citations (list)
        _items = []
        if self.citations:
            for _item_citations in self.citations:
                if _item_citations:
                    _items.append(_item_citations.to_dict())
            _dict['citations'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TranscriptTool from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "status": obj.get("status"),
            "queries": obj.get("queries"),
            "citations": [Citation.from_dict(_item) for _item in obj["citations"]] if obj.get("citations") is not None else None,
            "type": obj.get("type")
        })
        return _obj


